# Generated by Django 4.2.25 on 2025-10-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Listing', '0003_alter_listing_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('HOUSE', 'House'), ('APARTMENT', 'Apartment'), ('CABIN', 'Cabin'), ('VILLA', 'Villa'), ('CAR', 'Car'), ('BOAT', 'Boat'), ('OTHER', 'Other'), ('office', 'Office'), ('land', 'Land')], max_length=50),
        ),
    ]
